services:
  komga:
    image: gotson/komga
    container_name: komga
    environment:
      - TZ=Europe/Minsk
      - PUID=1000
      - PGID=1000
    volumes:
      - /docker/config/komga:/config
      - /data:/data
    ports:
      - 25600:25600
    restart: unless-stopped
